### ISSUE TITLE
[documentation] function _version_info._get_version_string()

### ISSUE THREAD

**Issue by Zeh-Marschke** [GuenterQuast/PhyPraKit#4]
In the description for PhyPraKit should be added the function _version_info._get_version_string(). 
Or should be used the constant __version__ to print out the current version number?

When I import modules, I want do document the current versions of the modules I use. Therefore, I print out the version numbers, to get a survey.

**Comment by GuenterQuast** [comment]
die Implementerierung ist so dass sie den üblichen Standards folgt; 
nach Import eines Moduls bekommt man die Versionsnummer mit

PhyPraKit.__version__
