### ISSUE TITLE
xyFit - part of the legend in the plot appears more than once

### ISSUE THREAD

**Issue by Zeh-Marschke** [GuenterQuast/PhyPraKit#7]
Hello Günter,
for the Praktikum 1, I use PhyPraKit (directly, without yaml) . For task 2.2 in "Praktikumsvorversuch - Datenverarbeitung am Beispiel des Pendels" I use a fit:
```
    def model_harmonic_oscillator(x, A = 0.8, omega=4., phi0=0.):
          return A * np.cos(omega * x + phi0)  
   fit = ppk.xyFit (model_harmonic_oscillator, t, acc, sx = t_errors, sy = acc_errors,
        axis_labels = [xlabel, ylabel], data_legend = label, model_legend = model_label,
        return_fitObject = True, quiet = True)
```
When I run this part, a lovely plot is produce. When I run it a second time, in the legend of the plot, the result for A, omega, phi0 and $\chi^2/n_{dof}$ appears a second time. When I run it a third time, it appears a third time and so on.
I've looked into the source code, but I could not realize, where the error (?) is located.
My workaround; ensure, that this part is run only once!
Andreas (Zeh-Marschke, wissbegieriger Student im 3. Semester)

**Comment by Zeh-Marschke** [comment]
I can't clear the plot, because I do not reach the plot-Object!

**Comment by GuenterQuast** [comment]
Fixed with latest Update
